[package]
name = "contentful"
version = "0.1.0"
authors = ["Saju Thankappan <sajuthankappan@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
log = "0.4.11"
reqwest = { version = "0.10.7", features = ["json"]}
serde_json = "1.0.57"
serde = "1.0.114"

[dev-dependencies]
dotenv = "0.15.0"
env_logger = "0.7.1"
serde = { version = "1.0.114", features = ["derive"]}
tokio = { version = "0.2.22", features=["macros", "rt-threaded"]}
