[package]
name = "contentful"
version = "0.2.0"
authors = ["Saju Thankappan <sajuthankappan@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Contentful API Rust Client"
homepage = "https://github.com/sajuthankappan/contentful-rs"
repository = "https://github.com/sajuthankappan/contentful-rs"
readme = "README.md"
keywords = ["contentful", "cms"]
categories = ["api-bindings"]

[dependencies]
log = "0.4.11"
reqwest = { version = "0.10.8", features = ["json"]}
serde_json = "1.0.59"
serde = "1.0.117"

[dev-dependencies]
dotenv = "0.15.0"
env_logger = "0.8.1"
serde = { version = "1.0.117", features = ["derive"]}
tokio = { version = "0.2.22", features=["macros", "rt-threaded"]}
