[package]
name = "contentful"
version = "0.5.3"
authors = ["Saju Thankappan <sajuthankappan@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Contentful API Rust Client"
homepage = "https://github.com/sajuthankappan/contentful-rs"
repository = "https://github.com/sajuthankappan/contentful-rs"
readme = "README.md"
keywords = ["contentful", "cms"]
categories = ["api-bindings"]

[dependencies]
getset = "0.1.1"
log = "0.4.14"
reqwest = { version = "0.11.3", features = ["json"]}
serde_json = "1.0.64"
serde = "1.0.126"
chrono = { version = "0.4.19", features= ["serde"]}

[dev-dependencies]
anyhow = "1.0.40"
dotenv = "0.15.0"
env_logger = "0.8.3"
serde = { version = "1.0.126", features = ["derive"]}
tokio = { version = "1.6.1", features=["full"]}
